### PR TITLE
build.scala cleanup (preparation for fixing android-tests paths)

### PR DESCRIPTION
**Pull request by aginiewicz**
Some clean-ups to build.scala. Especially, I separated settings common for
android and android_tests into android_common references by both, also copying
needed jars and shared objects into android_tests as well.

### CODE REVIEW

**Comment by aginiewicz** [comment]
I've rebased this on top of merged changes

**Comment by aginiewicz** [comment]
I found way to silence warnings. It seems, that tests use installed application (that's why it must be installed before usage), thus all dependencies are inside, and we need only very thin (scala&android-only) layer. That's why I decided to upload second proguard.cfg, with scala-only related entries. I believe this commit can actually close both, issues #31 and #32, and makes the config a bit cleaner.

**Comment by ajhager** [comment]
I have added you as a collaborator. Feel free to merge changes, and I will keep up with it the best I can. I am in the middle of a move and job change for the next 3 weeks.

**Comment by aginiewicz** [comment]
I'm in progress of rewriting this to support recently released sbt-android 0.7+, so this commit can be safely ignored.

**Pull request closed without merging**
