### PR TITLE
Couple IntelliJ Idea support improvements

### PR DESCRIPTION
**Pull request by pkoperek**
Related to issue https://github.com/ajhager/libgdx-sbt-project.g8/issues/90

Feel free to close (especially if You don't like the SNAPSHOT versions or the sbt-idea plugin :))

### CODE REVIEW

**Comment by aginiewicz** [comment]
Hi, thanks for your work! I will say what I think, but I will leave final decision to @ajhager as he is project owner.

I think It's not a matter of us liking or not liking Idea in snapshot, but I know different people use different environments - so if we include one, we should do so for other (ScalaIDE and Emacs to name two major ones) - and any user will not like situation that we force him to pull in not needed dependencies.

Can you rework it a bit to not include the IDE dependent parts in template (for example leave only those changes that work with "plain text editor+sbt" solution) and move all IDE related changes into Wiki about IDEs? This is I think a better place for this: https://github.com/ajhager/libgdx-sbt-project.g8/wiki/IDE-Plugins - we are accepting changes/pull requests there as well :)

Hope it makes sense :)

**Comment by pkoperek** [comment]
Sure - no problem :)

**Comment by ajhager** [comment]
I am going to defer to @aginiewicz on this one, as I have moved on from the project for the foreseeable future. I tend to agree that having editor specific code in the base template is generally not a good idea though. Thank you for the hard work.

**Comment by ajhager** [comment]
Once again, thank you for your work. Unfortunately, I do not think this is something I would like to merge.

**Pull request closed without merging**
