### PR TITLE
rebase of desktop proguard

### PR DESCRIPTION
**Pull request by aginiewicz**
I've rebased last pull request about proguard for desktop. There were few minor mistakes, not I've actually run more tests (including applications with assets). It cuts simple project by 10mb (to 6 from 16), most of which is platform dependent stuff.

I think that separate building of platform dependent libraries can be considered later.

(note: This was https://github.com/ajhager/libgdx-sbt-project.g8/pull/50 but I decided that mavenization of project touched build.scala in so many places,that it was easier to make new, fresh pull request. I'm linking it, so discussion below it does not disappear).

### CODE REVIEW

**Comment by ajhager** [comment]
I am working on this. I've got testing setup for all 3 desktop platforms now so I can make sure this is going to working correctly.

**Comment by aginiewicz** [comment]
great :) I'm regularly testing on Linux and Windows as I have it in my project, but not Mac, so if you got that too, I'd be very interested to see if it works there as well :)

**Comment by aginiewicz** [comment]
btw, about making platform-dependent .jars, I'd say we wait till sbt-android proguard filtering stabilizes, then we could create one rule set per Win/Lin/Mac/Android and one for common, and merge them (like we do with proguard files, but with 3 in desktop) - that way we could use single rule to eliminate gwt files on all platforms (or default font and/or shader)

**Comment by aginiewicz** [comment]
I've noticed, that provided dependencies were wrongly included. Not it's fixed, and used to exclude proguard-base in standard manner.

**Comment by aginiewicz** [comment]
I've rebased this one again on top of latest changes, with one intermediate pull request with simple updates.

**Pull request merged**
