### PR TITLE
first version of desktop JAR assembly using proguard

### PR DESCRIPTION
**Pull request by aginiewicz**
It still needs some work, probably better filtering of backend (we just include everything) and some fixes to possible bugs due to:

```
[info] Note: there were 3 unresolved dynamic references to classes or interfaces.
[info]       You should check if you need to specify additional program jars.
[info] Note: there were 14 accesses to class members by means of introspection.
[info]       You should consider explicitly keeping the mentioned class members
[info]       (using '-keep' or '-keepclassmembers').
```

but first 3 are from javax.jnlp and seems to be not essential, and introspection warnings are not critical I think.

For my simple test project (pong) I've got jar file that was 6.2mb instead of 16mb, so almost 10mb was cut and game still works nicely.

### CODE REVIEW

**Comment by aginiewicz** [comment]
I've tried to strip utils, opencl and opengles but it just saved 100k. Most of those 6mb I mentioned are from native libraries for Win/Lin/Mac - it is 3mb. Classes from lwjgl are about 1mb and scala 1.5mb. 0.3mb is libgdx itself and then there are ogg and mp3 decoders.

I think that if we want to have .jar file that is compatible with all Win/Lin/Mac, we cannot strip it down too much due to large binary libraries.

btw, I've forgot about asset directory. It is included in resulting jar now.

**Comment by ajhager** [comment]
I am about to try this out. Yeah, we will want to have a desktop build solution that includes all 3 platform's natives, but people often make platform specific builds. It could be useful to have tasks for building small, specific jars.

**Comment by aginiewicz** [comment]
if we decide on form of option to pick platform(s), it should be pretty easy to add filters to this and exclude some extra files.

**Comment by ajhager** [comment]
I am in the process of creating an sbt plugin to use https://github.com/stbachmann/JarWrapper for creating platform specific distributions, so I definitely think it will be useful.

**Comment by aginiewicz** [comment]
nice one, wasn't aware of JarWrapper. So maybe we should always create .jar, -win.jar, -lin.jar and -mac.jar in our proguard step?

As other choice I think we could create .jar without any .dll/.so (to proguard once) and repackage the jar later? Using for example jar command like in http://docs.oracle.com/javase/tutorial/deployment/jar/update.html or something like that?

**Comment by aginiewicz** [comment]
I've prepared https://github.com/ajhager/libgdx-sbt-project.g8/pull/61 that merges nicely and has some issues fixed.

**Pull request closed without merging**
