### PR TITLE
Upgrade Scala and SBT, switch Android plugin, remove iOS plugin (for now)

### PR DESCRIPTION
**Pull request by aginiewicz**
This big commit updates Scala to 2.11.1 and SBT to 0.13.5. It was possible
because of new Android plugin. This template now uses
https://github.com/pfn/android-sdk-plugin plugin.

Directory layout of project was changed to mirror those of official
gdx-setup.jar, though proguard rules are different - they are
merge of rules from old project, gdx-setup.jar template rules and
official android rules from proguard-android.txt.

Proguard rules might still need some polishing, there are warnings,
but they seem not influence normal working of Libgdx, so they
are ignored for now. If something does not work due to bad proguard
rule, open ticket and it will be fixed in template.

Last, but not least, I disabled iOS code for now, due to few reasons:
- https://github.com/ajhager/libgdx-sbt-project.g8/issues/78
- https://github.com/roboscala/sbt-robovm/issues/10
- default template from gdx-setup.jar looks different (it has three files)
- I don't have iOS nor Mac to test/fix this stuff

That's why I decided to remove those files and publish what I already got,
and wait for patches from someone who has iOS or Mac and can test/fix
iOS support in new template.

### CODE REVIEW

**Comment by aginiewicz** [comment]
as side not - this now works quite well in emulator (x86 emulator with gpu acceleration, started on linux with command:

```
emulator -avd <name> -qemu -m 512 -enable-kvm
```

running premade Galaxy Nexus AVD on Android 4.4.2 AVD and Intel Atom (x86) image and host GPU.)

At least that's what I tested.

**Comment by aginiewicz** [comment]
I've noticed there is already new version of plugin, and that I left some old comments. Last commit is cosmetic.

**Comment by ajhager** [comment]
This all looks great. Checking it out now.

**Comment by aginiewicz** [comment]
actually it worked ok, warnings come from higher level in current version of rules, so I had to -dontwarn macros in my project. Template was ok.

**Comment by ajhager** [comment]
Looks like it is working well.

**Comment by ajhager** [comment]
I will work on getting iOS support back up and running.

**Comment by aginiewicz** [comment]
Great! One more thing - icons and style.xml are from gdx-setup.jar template. I think it accounts for fair use (there is no license for those files in gdx-setup.jar or I haven't found it). Do you think we should contact them about it?

**Pull request merged**
